[toolchain]
package_manager = "npm"

[features]
seeds = true
skip-lint = false

[programs.devnet]
basingamarket = "2Gg6XUdXVqhSBwiCitDXBomY3JScusUcgSQckdYivv8D"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --workspace"
